language: cpp
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsoil-dev libglew-dev
  - wget https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz
  - sudo tar xvf cmake-3.5.2-Linux-x86_64.tar.gz -C /usr --strip-components=1
compiler: gcc
script: make test
