#ifndef EON_ENTITY_COMPONENTS_COMPONENTS_H
#define EON_ENTITY_COMPONENTS_COMPONENTS_H

namespace eon {
namespace entity {
enum ComponentType {
  DEFAULT,
  RENDER_COMPONENT,
  TRANSFORM_COMPONENT,
  CAMERA_COMPONENT
};
}
}

#endif
